### ISSUE TITLE
It only detect single quote `'` to be trimmed

### ISSUE THREAD

**Issue by krehwell** [isomoar/vim-css-to-inline#3]
hey, first of all, great plugin.

is that possible to get rid to double quote as well?
ex: 
```javascript
{
    paddingLeft: "1rem"
}
``` 
pressing `fis` will make it: 
```css
{
    padding-left: "1rem"
}
```

expected result: 
```css
{
    padding-left: 1rem
}
```
